[template.environment]
  API_KEY = 'MC5ZTlRTLVJBQUFDRUF4S2pr.AAvvv73vv70xeTLvv73vv70U77-977-977-977-977-977-9fO-_vSzvv71v77-977-977-9VSoE77-9Je-_vVUF'
  AIRTABLE_API_KEY = 'keyBoOQtqfdUPjenw'
  API_KEY_BASE_ID = 'appf9C9YsV8j99UG3'

[build.environment]
  API_KEY = 'MC5ZTlRTLVJBQUFDRUF4S2pr.AAvvv73vv70xeTLvv73vv70U77-977-977-977-977-977-9fO-_vSzvv71v77-977-977-9VSoE77-9Je-_vVUF'
  AIRTABLE_API_KEY = 'keyBoOQtqfdUPjenw'
  API_KEY_BASE_ID = 'appf9C9YsV8j99UG3'